- code/game/objects/items/weapons/storage/backpack.dm
Fixes https://github.com/tgstation/-tg-station/issues/7432
> fixes dufflebag max weight class

- code/game/objects/items/weapons/storage/secure.dm
:moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag:
> Fix syndicate briefcase not having cash.

- code/modules/admin/verbs/randomverbs.dm
You hear the voice of the badmin in your head...
> Hear the voice of the chosen deity in your head.

- code/__DEFINES/combat.dm
- code/modules/flufftext/TextFilters.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/living/say.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/mob_helpers.dm
- code/modules/projectiles/projectile.dm
- code/modules/reagents/Chemistry-Goon-Medicine.dm
- code/modules/reagents/Chemistry-Reagents/Consumable-Reagents/Drink-Reagents/Alcohols.dm
- code/modules/reagents/Chemistry-Reagents/Consumable-Reagents/Drink-Reagents/Drinks.dm
- code/modules/reagents/Chemistry-Reagents/Consumable-Reagents/Food-Reagents.dm
- code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm
- html/changelogs/dannno-slurring-7650.yml
Let me know if I missed anything.
> PROPER SLURRING

- code/modules/hydroponics/grown.dm
- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/guns/projectile.dm
fixes #7647
Guns now spend ammunition when you shoot your stupid face off
they also have a much better and more natural suicide message
also you yell BANG when you kill yourself with a banana now
> Fixes #7647

- code/game/objects/items/toys.dm
Fixes crayons causing runtime errors.
> Add initialize for crayons and fix runtime error.

- code/game/atoms_movable.dm
> Fixes not being able to move from a single lattice.

- code/game/objects/structures/lattice.dm
- html/changelogs/xxalpha-cablefix.yml
> Fixes cables being destroyed when creating plating out of catwalk space.

- code/game/objects/items/weapons/explosives.dm
Fixes https://github.com/tgstation/-tg-station/issues/7802
> Fixes the C4 being planted on the DA.

- code/modules/clothing/spacesuits/hardsuit.dm
Fixes https://github.com/tgstation/-tg-station/issues/8637
> Fixes atmos hardsuit pathing.

- code/modules/mob/living/simple_animal/hostile/carp.dm
jesus christ think of all those g's. jesus fucking christ. what have we done
fixes #8681
> fixes critical priority bug

- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/human/species.dm
Fixes https://github.com/tgstation/-tg-station/issues/8798
> Fixed inbuilt jetpack not working for syndicate hardsuit.

- code/modules/admin/create_object.dm
Added /obj/item/stack path to the Quick Create Object option in Game Panel.
> Added /obj/item/stack path to Game Panel.

- code/modules/research/designs.dm
- code/modules/research/designs/mechfabricator_designs.dm
- code/modules/research/protolathe.dm
This has been bothering me for a long time.
> Fixes french invasion.

- code/modules/projectiles/guns/syringe_gun.dm
Fixes https://github.com/tgstation/-tg-station/issues/9070.
> Fixed syringes being chambered when stored in a backpack.

- code/game/objects/items/crayons.dm
- code/game/objects/items/toys.dm
Fixes https://github.com/tgstation/-tg-station/issues/9217
> Fixed unlimited uses crayons not being unlimited.

- code/modules/surgery/surgery_step.dm
Fixes https://github.com/tgstation/-tg-station/issues/9174
> Fixed surgery closing step not removing bleeding overlay.

- code/ATMOSPHERICS/datum_pipeline.dm
Added some more words and special characters to an error string.
> Pipe Panic

- code/game/objects/items/weapons/cigs_lighters.dm
- html/changelogs/xxalpha-ash.yml
Fixes the rest of https://github.com/tgstation/-tg-station/issues/2490
> Fixed a couple of small problems with smoking pipes.

- code/game/machinery/doors/windowdoor.dm
- html/changelogs/xxalpha-spacehulks.yml
Fixes https://github.com/tgstation/-tg-station/issues/5328
> Hulks can now break windoors.

- code/game/objects/items/stacks/stack.dm
- code/game/turfs/simulated/floor/plating.dm
Fixes https://github.com/tgstation/-tg-station/issues/6282
> Fixed cyborg floor tiles being infinite.

- code/game/objects/items/weapons/cigs_lighters.dm
- code/game/objects/items/weapons/twohanded.dm
- code/modules/power/singularity/emitter.dm
- code/modules/projectiles/projectile.dm
- html/changelogs/xxalpha-petethegoat.yml
~~Unreported.~~
edit: Also Fixes https://github.com/tgstation/-tg-station/issues/5782
Weird ass runtime, but it happened at least once somehow. Miauw forgot to fix it so here it is.
edit: Also Fixes https://github.com/tgstation/-tg-station/issues/6748
edit: Also Fixes https://github.com/tgstation/-tg-station/issues/6283
edit: Also Fixes (unreported?) emitters not being reflectable.
> A handful of fixes.

- code/game/gamemodes/changeling/powers/revive.dm
- code/modules/projectiles/guns/magic/staff.dm
- html/changelogs/xxalpha-memech.yml
~~I am not sure what caused changeling revival to break, but this makes it work. It didn't need this before, so I am sure someone broke it somewhere else.~~
Whatever changed, now it works with the stat change line pushed to the end.
Fixes https://github.com/tgstation/-tg-station/issues/9456
> Fixed Changeling Revival

- code/game/objects/items.dm
- code/game/objects/items/toys.dm
- code/game/objects/items/weapons/handcuffs.dm
- code/game/objects/items/weapons/tools.dm
- code/game/objects/items/weapons/weaponry.dm
- code/modules/assembly/holder.dm
- code/modules/paperwork/paperbin.dm
Fixes https://github.com/tgstation/-tg-station/issues/3205 - Card decks being in the hands and pockets at the same time
Fixes https://github.com/tgstation/-tg-station/issues/9428 - Storages not rearranging their contents in some cases (such as removing paper bins and card decks)
> Card deck fixes and storage fixes.

- code/game/objects/items/devices/PDA/PDA.dm
Fixes https://github.com/tgstation/-tg-station/issues/9763
> Fixed PDA accepting items when spessmen can't drop items.

- code/datums/wires/wires.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/modules/recycling/disposal.dm
Fixed inserting items in PDAs, it now works properly.
Reenabled ability to drop items inside disposal bins.
> Fixed hacking from inside machines.

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
Fixes https://github.com/tgstation/-tg-station/issues/1328
> Fixed AI seeing more than it should when the Eye is moved to the Core.

- code/game/objects/structures/table_frames.dm
- code/game/objects/structures/windoor_assembly.dm
Like table construction.
Please report more infinite stack cases.
> Fixes infinite cyborg stack usage on a couple of things.

- code/game/objects/items/weapons/RCD.dm
Fixes https://github.com/tgstation/-tg-station/issues/9925
> Fixes RCD wall deconstruction runtime.

- code/modules/mob/living/carbon/brain/MMI.dm
- code/modules/surgery/surgery_step.dm
Also fixed the sawing surgery step not checking for monkeys or aliens. This resulted in no feedback messages when operating on monkeys or aliens.
> Fixed not being able to insert a brain into an MMI.

- code/game/objects/items/devices/radio/electropack.dm
Fixes https://github.com/tgstation/-tg-station/issues/3409
> Fixed being able to interact with electropack while wearing it.

- code/modules/clothing/clothing.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/misc_special.dm
- code/modules/clothing/masks/breath.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/masks/miscellaneous.dm
Fixes https://github.com/tgstation/-tg-station/issues/10205
> Fixed not being able to eat with adjusted masks.

- code/game/objects/items/weapons/storage/fancy.dm
> Restores ability to insert lighters into cigarette packs.

- code/game/gamemodes/nuclear/nuclearbomb.dm
Resolves https://github.com/tgstation/-tg-station/issues/10377
> Added error message to nuke's deconstruction for clarity.

- code/game/objects/items/stacks/sheets/mineral.dm
Fixes https://github.com/tgstation/-tg-station/issues/10429
> Fixed plasma not stacking.

- .gitignore
so I don't have to see all the map backups in git gui
> Added *.backup to gitignore

- code/__HELPERS/icon_smoothing.dm
Fixes current smoothing issues.
> Readds spawn() proc to icon smoothing code.

- code/game/gamemodes/changeling/powers/augmented_eyesight.dm
- code/modules/mob/living/simple_animal/hostile/statue.dm
- html/changelogs/xxalpha-changeling_vision.yml
Fixes https://github.com/tgstation/-tg-station/issues/10297
Also fixes an exploit that allows you to get permanent x-ray.
E: Fixes https://github.com/tgstation/-tg-station/issues/7386
> Fixed changeling night vision and night vision spell.

- code/game/mecha/mech_fabricator.dm
Fixes https://github.com/tgstation/-tg-station/issues/10759
> Changed mechfab RD console detection to oview.

- code/game/turfs/turf.dm
Fixes https://github.com/tgstation/-tg-station/issues/7934
> Fixed cables floating in space after RCD decon.

- code/game/gamemodes/changeling/powers/mutations.dm
- code/modules/mob/inventory.dm
Fixes https://github.com/tgstation/-tg-station/issues/8885
> Fixed changeling shields dropping when ling is prone.

- code/game/objects/items/weapons/cards_ids.dm
- html/changelogs/xxalpha-rw_agent.yml
~~Forging is now on CtrlClick~~
It's an alert window.
> Made Agent IDs rewrittable.

- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/items/weapons/storage/storage.dm
Fixes https://github.com/tgstation/-tg-station/issues/10701
E: This bug happens with any stack object. Fixed for all stack objects.
> Fixed storage not updating when joining cable coils.

- code/datums/uplink_item.dm
- code/modules/surgery/organs/cybernetic_implants.dm
Reverts tgstation/-tg-station#10887
No reason to revert this because you're offended I didn't state a very visible change. Implying I tried to sneak in changes in a 13 lines changed overall PR is ridiculous.
> Revert "Revert "Removed anti-drop implant from NukeOps uplink.""

- code/game/turfs/turf.dm
Fixes https://github.com/tgstation/-tg-station/issues/10926
> Fixed cable being deconstructed by walls.

- code/modules/clothing/suits/toggles.dm
Fixes https://github.com/tgstation/-tg-station/issues/11083
> Fixed inbuilt jetpacks dropping when suit is deleted.

- code/controllers/configuration.dm
- code/modules/admin/verbs/fps.dm
- code/modules/mob/mob_movement.dm
- config/config.txt
Reverts tgstation/-tg-station#11159
game is not playable
Fixes #11466
> Revert "Smooth out gliding so movement isn't (as) jerky"

- code/game/objects/effects/effect_system/effects_foam.dm
- html/changelogs/xxalpha-PLmD_69pXpk.yml
Foam now spreads under things even if they are dense.
> Tweaked foam spread logic, foam layer.

- code/game/objects/items/stacks/stack.dm
- code/modules/power/cable.dm
Fixes https://github.com/tgstation/-tg-station/issues/11520
Fixed cable pieces taken from a coil being of a different color than the coil.
> Fixed a couple of bugs with cable coils.

- code/modules/mob/living/simple_animal/slaughter/slaughter.dm
- code/modules/mob/living/simple_animal/slaughter/slaughterevent.dm
Fixes https://github.com/tgstation/-tg-station/issues/11540
> Fixed wizard slaughter demons not getting bloodcrawl

- code/modules/mining/mine_turfs.dm
Fixes https://github.com/tgstation/-tg-station/issues/11621
> Singularity won't pull asteroid/plating turfs anymore.

- code/modules/mob/living/carbon/human/species.dm
Fixes https://github.com/tgstation/-tg-station/issues/11733
> Fixed eye wear overriding see_invisible when it shouldn't.

- code/datums/material_container.dm
Fixes https://github.com/tgstation/-tg-station/issues/11771
> Fix autolathe rejecting stacks.

- code/modules/research/designs.dm
- code/modules/research/designs/weapon_designs.dm
- code/modules/research/protolathe.dm
- code/modules/research/rdconsole.dm
Fixes https://github.com/tgstation/-tg-station/issues/11823
> Fixed protolathe not printing things that required reagents.

- code/modules/mob/living/simple_animal/bot_swarm/swarmer.dm
> Fix swarmer effect being affected by spacewind

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Only chew visible cables. Will kill mouse if powered.
> Adds a very small chance of mice chewing power cables.

- code/_onclick/hud/alert.dm
- code/game/objects/buckling.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/carbon/update_icons.dm
Fixes https://github.com/tgstation/-tg-station/issues/12763
> Fixed cyborgs not being able to unbuckle with alarm button

- code/__HELPERS/type2type.dm
- code/game/objects/items/crayons.dm
- code/game/objects/items/toys.dm
- code/game/objects/items/weapons/clown_items.dm
- code/game/objects/structures/artstuff.dm
Edit: Changed it so only darker colors make the window opaque.
Changed only the colour var.
Painting or cleaning tinted windows will not make them see through.
-------------
My first PR.
Paint them with spray cans, clean them with soap.
Also renamed two vars to be less confusing.
> Made it possible to paint windows to make them opaque.

- code/modules/mob/say.dm
> wastes a get

- code/__HELPERS/icon_smoothing.dm
Fixes https://github.com/tgstation/-tg-station/issues/13476
Issue only affects turfs and happens only because something something map loader.
> Fixes away mission icon smoothing.

- code/game/machinery/doors/airlock.dm
Fixes https://github.com/tgstation/-tg-station/issues/13606
> Fixes a specific airlock animation case.

- code/__HELPERS/icon_smoothing.dm
- code/modules/awaymissions/zlevel.dm
Fixes https://github.com/tgstation/-tg-station/issues/13617
Also improved the speed a tiny little bit.
> Fixed icon smoothing in loaded maps for good.

- code/game/machinery/doors/airlock.dm
- html/changelogs/xxalpha-airlocking.yml
I apologize to all my silicon friends.
This should close an issue but I can't find it, maybe it's already closed.
> Fixed not being able to bolt and unbolt operating doors.

- code/game/machinery/rechargestation.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
Because wet floors are not clean floors.
> Adds a bottle of drying agent spray to janiborg.

- code/modules/power/tesla/energy_ball.dm
> fixes tesla engine being called energy eall

- code/modules/mob/living/life.dm
This fixes inbuilt jetpacks action buttons.
> Fix recursive action buttons

- code/modules/mob/living/carbon/human/examine.dm
Fixes https://github.com/tgstation/-tg-station/issues/4833
> Fixes covering clothing not hiding gender on examine()

- code/game/gamemodes/changeling/powers/biodegrade.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/handcuffs.dm
- code/modules/clothing/suits/miscellaneous.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/mob/living/carbon/human/update_icons.dm
Fixes https://github.com/tgstation/-tg-station/issues/5819 : 
- Now it's possible to resist out of a straight jacket (takes roughly 5 minutes)
- Straightjacketing someone who is handcuffed will not remove the handcuffs
> Fixes the straightjacket

- code/controllers/subsystem/shuttles/assault_pod.dm
- code/game/area/Space Station 13 areas.dm
- code/modules/admin/verbs/adminjump.dm
- code/modules/events/anomaly.dm
- code/modules/events/anomaly_bluespace.dm
- code/modules/events/anomaly_flux.dm
- code/modules/events/anomaly_grav.dm
- code/modules/events/anomaly_pyro.dm
- code/modules/events/anomaly_vortex.dm
- code/modules/mob/interactive.dm
Closes https://github.com/tgstation/-tg-station/issues/5669
This has been fixed for a year now but the issue was never closed. Changed the proc to safepick() but either proc is safe.
Edit: As phil pointed out in that issue, there was a bunch of other instances of ``pick(get_area_turfs())`` so I changed them all to use safepick().
> jump to area uses safepick

- code/game/machinery/computer/law.dm
- code/game/objects/items/weapons/AI_modules.dm
- code/game/objects/structures/ai_core.dm
Fixes https://github.com/tgstation/-tg-station/issues/5532
Pro tip, you can't upload laws directly to a live AI.
> Installing laws to an empty AI core will now use install() instead of snowflake.

- code/controllers/subsystem/timer.dm
- code/datums/wires/apc.dm
- code/game/machinery/doors/airlock.dm
- code/modules/power/apc.dm
Fixes https://github.com/tgstation/-tg-station/issues/1130
> Changed APC wire pulsing and airlock autoclose() to use timers.

- code/game/machinery/camera/camera.dm
- code/game/machinery/camera/motion.dm
Fixes https://github.com/tgstation/-tg-station/issues/14985
Fixes https://github.com/tgstation/-tg-station/issues/14993
> Fixed camera/New().

- code/modules/mob/living/bloodcrawl.dm
Fixes https://github.com/tgstation/-tg-station/issues/15007
> Fixed bloodcrawl move setting loc to null.

- code/game/gamemodes/malfunction/Malf_Modules.dm
Fixes https://github.com/tgstation/-tg-station/issues/15170
> Fixed doomsday device spamming.

- code/__HELPERS/game.dm
- code/__HELPERS/unsorted.dm
- code/datums/diseases/wizarditis.dm
- code/game/mecha/equipment/tools/other_tools.dm
Also fixes wormhole generator.
> Fixes wizarditis teleport

- code/modules/projectiles/guns/energy/special.dm
It's the future.
:cl:
rscadd: Kinetic accelerators now reload automatically.
/:cl:
> Kinetic accelerators automatically reload.

- tools/mapmerge/map_helpers.py
Any existing duplicate entries will be corrected by normal usage of the mapmerge. They don't cause any problems besides being redundant data in the files, causing bloat.
Also changed merge_map() to reuse keys in a better way, reducing line changes.
> [Mapmerge] Fixed bug that caused duplicate entries. Reduced line changes.

- tools/mapmerge/map_helpers.py
tuples instead of lists and sets
> [mapmerger] small patch

- code/modules/awaymissions/zlevel.dm
Fixes runtime error when loading templates, not the lighting bug related to loading templates.
> fix template loading runtimes

- code/__HELPERS/icon_smoothing.dm
- code/controllers/subsystem/icon_smooth.dm
- code/game/objects/structures.dm
- code/game/objects/structures/false_walls.dm
- code/game/objects/structures/tables_racks.dm
- code/game/objects/structures/window.dm
- code/game/turfs/simulated.dm
- code/game/turfs/simulated/floor/fancy_floor.dm
- code/game/turfs/simulated/walls_reinforced.dm
- code/game/turfs/turf.dm
- code/modules/atmospherics/environmental/LINDA_turf_tile.dm
- code/modules/holodeck/turfs.dm
- code/modules/shuttle/shuttle.dm
- tgstation.dme
This prevents the server from hanging if there's too much smoothing going on at server start, as is the case with lavaland.
Fixes https://github.com/tgstation/-tg-station/issues/16051
> icon smooth ss

- code/controllers/subsystem/gamemaster.dm
- tgstation.dme
experimental automated game master
> [s] experimental automated game master

- tools/mapmerge/map_helpers.py
fixed mapmerger writing last y incorrectly when converting to tgm
> Fixes mapmerger

- code/datums/material_container.dm
- code/game/machinery/droneDispenser.dm
Fixes https://github.com/tgstation/-tg-station/issues/17442
:cl:
bugfix: Fixed drone dispenser multiplying glass or metal.
/:cl:
> Fixed drone dispenser material exploit

- tools/mapmerge/mapmerger.py
> mapmerge creates edited map before merge backups

- code/game/objects/items/nuke_tools.dm
Clean up the code a little bit to maybe prevent a bug from happening?
Fixes https://github.com/tgstation/-tg-station/issues/17804 ?
> Clean up plutonium core a bit

- code/__DEFINES/misc.dm
- code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
cuff_resist for carbons can be called with cuff_break = 2 as an argument, which will allow the mob to instantly break cuffs
> aliens break cuffs instantly

- _maps/map_files/TgStation/tgstation.2.1.3.dmm
- _maps/map_files/generic/z2.dmm
- _maps/map_files/generic/z6.dmm
- code/game/turfs/simulated/floor/plasteel_floor.dm
- code/game/turfs/simulated/floor/plating.dm
Fixes https://github.com/tgstation/tgstation/issues/18104
Just a heads up, these repaths are bound to cause visual bugs with current floor code.
> Fixed two wrong types for plating

- code/modules/power/singularity/singularity.dm
fixes #18062 
bugfix for #18082
> fixes singularity expanding and eating containment

- code/game/turfs/simulated/walls_misc.dm
Fixes https://github.com/tgstation/tgstation/issues/18097
> Fixed smooth shuttle walls not smoothing properly on rotation.

- code/game/objects/items/weapons/holy_weapons.dm
fixes dismembering chaplains to steal the godhand
> fixes godhand not deleting on drop

- code/game/objects/items/weapons/holy_weapons.dm
"The brim of the hat is as sharp as your wit. Throwing it at someone would hurt almost as much as disproving the existence of God."
> Makes the fedora holy weapon sharp and actually good

- code/modules/spells/spell_types/spacetime_distortion.dm
Fixes https://github.com/tgstation/tgstation/issues/19824
> Fixed Spacetime Distortion spell being upgradeable.

- code/__HELPERS/unsorted.dm
- code/game/machinery/porta_turret/portable_turret.dm
>in world
edited with profile
before:
after (subtypes = FALSE):
after (subtypes = TRUE):
after (subtypes = TRUE and type cache):
> bettering of get area procs

- code/__HELPERS/unsorted.dm
- code/game/machinery/porta_turret/portable_turret.dm
Remake of #19974, now working as intended.
> area procs again

- code/game/area/Space_Station_13_areas.dm
- code/world.dm
Also optimized process_teleport_locs() a little bit.
Fixes https://github.com/tgstation/tgstation/issues/20125
> Fixed area teleport not listing areas to teleport to

- code/modules/mob/living/carbon/human/species.dm
now we have
- harm(user, target, attacker_style)
- help(user, target, attacker_style)
- disarm(user, target, attacker_style)
- grab(user, target, attacker_style) 
procs for each action instead of the previous blob.
attacker_style is var/datum/martial
thanks razharas for helping me with dis.
> GIANT INTENT REFACTOR (separates it into 4 different harm, help, disarm and grab procs)

- code/game/objects/items/stacks/sheets/glass.dm
- tgstation.dme
:cl: BASILMAN YOUR MAIN MAN
fix: fixes people "walking over the glass shard!" when they're on the ground, changes message when incapacitated
/:cl:
only because i dont feel good when i dont make a pr for long.
> fixes people "walking over the glass shard!" when they're on the ground, changes message.

- code/game/objects/items/stacks/sheets/glass.dm
self-explanatory, now you dont always slide on glass you step on it too wow
#22258 fixed
> fixes my glass message tweak fuck-up

- code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
> fixes (#22685) swarmers eating catwalks with wires on them.

- tools/mapmerge/map_helpers.py
Fixes https://github.com/tgstation/tgstation/issues/23658
Changed the 'header' argument of writing functions to default to None.
> Map fixer patch - argument default

- code/modules/mining/lavaland/necropolis_chests.dm
> Buckling fix

- code/game/objects/items/weapons/storage/toolbox.dm
> i forgot old!

- code/game/objects/effects/contraband.dm
:cl: Pyko
fix: Fixed legit posters and map editing official/serial number for poster decals.
/:cl:
Fixes: https://github.com/tgstation/tgstation/issues/23900
> Poster fix

- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/TgStation/tgstation.2.1.3.dmm
Now these vending machines will be random in appearance on spawn.
Hope I used map merger right!
> replaces vending/cola with vending/cola/random on meta, delta, and box

- code/game/machinery/vending.dm
> proper \improper

- code/game/objects/items/weapons/storage/boxes.dm
> fixes boxes that dont use an illustration having writing on them

- code/game/turfs/turf.dm
- code/modules/spells/spell_types/spacetime_distortion.dm
No more shitty wavey sprite, now it looks like what a spacetime distortion looks like in real life.
Also it won't have a good chance of teleporting you into space anymore (unless you cast it in space).
> Improved the appearance of spacetime distortions.

- code/game/machinery/vending.dm
- code/modules/clothing/clothing.dm
this sat for 2 weeks and raz already reviewed it so can it not sit ANOTHER 2 weeks
edit: as of this edit this pr had sat for 3 fucking weeks in total where is @optimumtact when you need him
> support for shoes with height  (git unfucked version)

- code/modules/mob/living/carbon/human/species.dm
allows for species with different heights e.g to use the same hair and face system 
very naice very good.
tested and it works nice
> adds hair and face y offsets variables for species

- code/datums/riding.dm
- code/modules/mob/living/carbon/human/human.dm
> fixes shit formatting and grammar with human piggyback riding

- code/modules/food_and_drinks/kitchen_machinery/gibber.dm
- code/modules/mob/living/carbon/human/species.dm
:cl: basilman
fix: fixed species with no skin dropping skin when gibbed.
/:cl:
> fixes people with no skin/golems dropping skin when gibbed

- code/game/objects/items/weapons/storage/toolbox.dm
WOOPS
missing commit was the problemo
> fixes triple latched toolboxes spawning too often than anticipated

- code/datums/riding.dm
- code/modules/vehicles/speedbike.dm
> refactors how vehicles use offsets + multiseat

- code/game/gamemodes/devil/true_devil/_true_devil.dm
- code/game/gamemodes/miniantags/revenant/revenant.dm
- code/modules/mob/living/simple_animal/bot/floorbot.dm
- code/modules/mob/living/simple_animal/constructs.dm
- code/modules/mob/living/simple_animal/hostile/bear.dm
- code/modules/mob/living/simple_animal/hostile/bees.dm
- code/modules/mob/living/simple_animal/hostile/carp.dm
- code/modules/mob/living/simple_animal/hostile/faithless.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/dragon.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
- code/modules/mob/living/simple_animal/hostile/pirate.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
- code/modules/mob/living/simple_animal/hostile/syndicate.dm
- code/modules/mob/living/simple_animal/shade.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/mob_movement.dm
> Process_Spacemove proc improvement

- code/modules/projectiles/guns/ballistic/automatic.dm
:cl: LuigiBoi
spellcheck: Fixed gun desc typo
/:cl:
> Fixes spelling error

- code/modules/antagonists/disease/disease_mob.dm
:cl: Astral
add: Ghosts can now examine sentient diseases to see info
/:cl:
> Ghosts can now examine sentient diseases to see info

- code/modules/reagents/chemistry/reagents/drink_reagents.dm
- code/modules/vehicles/speedbike.dm
:cl: Basilman
fix: fixed BM Speedwagon offsets
/:cl:
> [Ready] Fixes BM Speedwagon offsets after they were broken by some DEGENERATE

- code/game/objects/items/implants/implant_stealth.dm
:cl: Basilman
fix: fixed agent box invisibility
/:cl:
:cry: hey a man's gotta do what a man's gotta do
> [s] [HOTFIX] Being bumped into and not just bumping into people makes you visible as agent box

- code/datums/action.dm
apparently requested and i am OBLIGED 
:cl: Basilman
balance: Increased agent box cooldown to 10 seconds
/:cl:
apparently people were exploiting it to get out of stuns and shit cuz its cooldown was too short
edit: clarification that you could never use the box while stunned or cuffed
> Increases agent box cooldown to 10 seconds

- code/game/objects/items/his_grace.dm
:cl: basilman
balance: mobs without an attached mind dont contribute towards his grace ascension
/:cl:
[why]: # balance
> mobs without an attached mind dont contribute towards his grace ascension

- code/modules/clothing/spacesuits/hardsuit.dm
> adds a period to captains hardsuit desc

- code/modules/mob/living/simple_animal/slime/slime.dm
:cl: Basilman
add: Slimes can now pass through grilles
/:cl:
[why]: # >iron mesh
>stops slime
shidfugkdugkd,xdhgks.
> Slimes can now pass through grilles because le slime

- code/modules/vehicles/bicycle.dm
> clean up Cyberboss's mess

- code/modules/spells/spell_types/hivemind.dm
> All hivemind powers now ignore antimagic

- code/modules/reagents/chemistry/reagents/other_reagents.dm
> Capitalizes Pax's reagent name

- code/modules/food_and_drinks/food/snacks_pizza.dm
:cl: Basilman
fix: Fixes Arnold Pizza having a slight flavor of pineapple
/:cl:
> Fixes Arnold Pizza having a slight flavor of pineapple

- code/modules/mob/living/living.dm
:cl: Basilman
fix: Fixed adminheal not curing various status effects
/:cl:
closes #42996
> Fixes adminheal not curing various status effects

- code/modules/mob/living/carbon/human/species_types/vampire.dm
they don't belong in this world
:cl: Basilman
add: Chaplain's holy whip now deals more damage to vampires.
/:cl:
vampire killer.
> Holy whip now deals more damage to vampires.

- code/modules/cargo/bounties/special.dm
:cl: Basilman
fix: Fixed certain alien organs (eyes, tongue, liver) not registering for organ bounty.
/:cl:
closes #42961
> Fixes certain alien organs (eyes, tongue, liver) not registering for organ bounty.

- code/game/objects/items/implants/implant_mindshield.dm
Fixes #42953 for real this time, the timer was only part of the issue, as I forgot to change a hivemembers check to look for minds and not bodies.
Looked into #43361 while i was at it, could not reproduce with or without one mind. Haven't tested with chaos induction but it looks like there's a possible runtime that would only occur on awoken vessels without One Mind(IE Chaos Induction), which I've patched out just in case that might be the cause.
fixes bugs
:cl: Kierany9
fix: Fixed the assimilation radar bug for real this time.
fix: Possibly fixed mindshield implants sometimes not working against vessels.
/:cl:
> Fixes the radar bugs for real

- code/modules/clothing/under/jobs/civilian.dm
> fixes clown suit datum runtime

- code/modules/admin/sql_ban_system.dm
Fixes #45123 and adds hivemind hosts to the banning panel
I have no idea how the admin tools work on the backend so tell me if i've goofed hard maintainers
This is purely admin shit that I'm not sure even needs to have a changelog
> Adds assimilation bans

- code/modules/mob/living/carbon/human/species.dm
see title and/or changelog, the biggest nerf to endgame hiveminds
(alt title: try hitting it really hard)
ngl, i just read this suggested somewhere and found it funny
:cl:
add: You can now bash awoken vessels over the head to deconvert them, just like revolutionaries
/:cl:
> Bashing people in the head has a chance to deconvert them during One Mind

- code/datums/elements/loomable.dm
Title.
Adds a second amount check to once the do_after() is done to prevent a possible epic dupe minecraft pay to win server lag machine server crash glitch.
Bugs are bad
:cl:
fix: You can no longer make extra cloth when looming cotton by spamming do afters.
/:cl:
> Fixes a possible dupe bug with looming

- code/modules/mob/living/carbon/human/_species.dm
old_species can be null
runtime bad uhuh
> Adds nullchecks in species code to prevent runtimes

- code/modules/mob/living/carbon/human/_species.dm
- code/modules/mob/living/carbon/human/species_types/plasmamen.dm
- code/modules/mob/living/carbon/human/species_types/skeletons.dm
- code/modules/surgery/organs/internal/liver/_liver.dm
- code/modules/surgery/organs/internal/liver/liver_golem.dm
- code/modules/surgery/organs/internal/liver/liver_plasmaman.dm
- code/modules/surgery/organs/internal/liver/liver_skeleton.dm
Fixes https://github.com/tgstation/tgstation/issues/76329
I DID A REAL STUPID MISTAKE WHILE CODING https://github.com/tgstation/tgstation/pull/76184 I AM SORRY
The signal was sending the fucking human instead of seconds_per_tick
Fixes a BUNCH of liver behavior including plasmamen livers not healing wounds
:cl:
fix: Plasma will now heal plasmamen properly
/:cl:
> [NO GBP] Fixes my fuckups with species livers

- code/controllers/subsystem/processing/quirks.dm
- code/datums/brain_damage/severe.dm
- code/datums/quirks/negative_quirks.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/modules/reagents/reagent_containers/cups/drinkingglass.dm
Like paraplegic, but instead of a horizontal half of your body being fucked, it's a vertical half!
Character customization and pure, undistilled human suffering.
:cl:
add: Added Hemiplegic quirk.
/:cl:
> Hemiplegic quirk

- code/game/objects/items/pillow.dm
Terrible idea I got from reading the comments in https://github.com/tgstation/tgstation/pull/76312
Because it's funny as hell and makes pillows work as an improvised non-lethal weapon, if you get sandstone bricks.
:cl:
add: You can now put sandstone bricks in pillows to... make them deadlier?
/:cl:
> You can put bricks inside pillows

- code/game/objects/structures/cat_house.dm
Capitalizes and adds a period to the inspection text of the cat house.
Grammar is good. I like grammar.
:cl:
spellcheck: Changed grammar in cat_house.dm
/:cl:
> Fixes grammar in cat_house.dm
