code/modules/power/power.dm
Couldn't wire singularity beacon on a catwalk, this fixes that and probably others.
=> Allows portable machines to be mounted on any turf that can have cables.

code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/stacks/stack.dm, code/modules/mining/equipment_locker.dm
Fixes  #8357.
Fixes being able to use zero amount glass sheet stacks to construct one side windows.
Fixes the ore redemption machine dropping zero amount stacks when deconstructed.
=> Fixes several zero amount stack bugs.

code/_compile_options.dm
~~Doubled crushing damage and added a chance to knock the victims unconscious to prevent baby screaming.~~
Increased crush damage to 15.
Fixes https://github.com/tgstation/-tg-station/issues/8862
=> Buffs airlock crushing.

code/_onclick/click.dm, code/game/gamemodes/abduction/machinery/experiment.dm, code/game/gamemodes/changeling/evolution_menu.dm, code/game/gamemodes/changeling/powers/augmented_eyesight.dm, code/game/machinery/Sleeper.dm, code/game/machinery/cryo.dm, code/game/machinery/machinery.dm, code/game/machinery/rechargestation.dm, code/game/mecha/mecha.dm, code/modules/mob/inventory.dm, code/modules/reagents/Chemistry-Machinery.dm, code/modules/recycling/disposal.dm, code/modules/surgery/cavity_implant.dm, code/modules/surgery/limb augmentation.dm, html/changelogs/xxalpha-itsakindofmagic.yml
Fixes https://github.com/tgstation/-tg-station/issues/8699 - Laser Eyes conflicting with X-ray vision
Fixes https://github.com/tgstation/-tg-station/issues/8486 - Cavity implant ignoring NODROP flag
Fixes https://github.com/tgstation/-tg-station/issues/8278 - Dropping things inside mechas - major thanks to Remie for this one
Fixes https://github.com/tgstation/-tg-station/issues/9206 - Dropping things in vents and machines - see directly above
Fixes https://github.com/tgstation/-tg-station/issues/8602 - Changeling augmented eyesight exploit
Fixes https://github.com/tgstation/-tg-station/issues/8646 - Medborgs able to insert their beakers into chem master and cryopods
Fixes https://github.com/tgstation/-tg-station/issues/8490 - Wrong parts for wrong limbs augmentations
=> A second handful of fixes.

code/game/objects/items/holotape.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/mob/living/carbon/human/human_movement.dm
Fixes runtime when attempting to close a locker when there are other lockers in the same turf.
Fixes runtime when things bump against holotapes and those things aren't mobs.
Fixes runtime when no shoes when i dont know, but null refs. (Fixes https://github.com/tgstation/-tg-station/issues/9877)
=> Fixes three runtimes.

code/_onclick/hud/action.dm, code/game/objects/items.dm, code/game/objects/items/weapons/tanks/jetpack.dm, code/modules/mob/living/life.dm
Resolves https://github.com/tgstation/-tg-station/issues/10322
I don't know if this is the best way to do it. I tested the case I wanted to work and existing action buttons (including spells and mime buttons) and everything works.
=> Added ability for items inside items to have action buttons.

code/LINDA/LINDA_turf_tile.dm, code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm, code/game/turfs/turf.dm
Fixes https://github.com/tgstation/-tg-station/issues/10528
Also removed a proc that is no longer used.
E: Also fixes nests overlays being deleted when unbuckling a mob (meaning the nest would go invisible).
=> Fixed gases deleting all overlays of a turf when spreading.

code/datums/material_container.dm, code/datums/wires/wires.dm, code/game/machinery/alarm.dm, code/game/machinery/autolathe.dm, code/game/machinery/bots/mulebot.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/syndicatebomb.dm, code/game/machinery/vending.dm, code/game/objects/items/devices/pizza_bomb.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/weapons/explosives.dm, code/modules/assembly/assembly.dm, code/modules/mining/ores_coins.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/power/apc.dm, code/modules/power/singularity/particle_accelerator/particle_control.dm, code/modules/research/rdmachines.dm
Fixes https://github.com/tgstation/-tg-station/issues/11373
Fixes https://github.com/tgstation/-tg-station/issues/11366
Everything with datum/wires object was changed.
Note: This does not fix qdel problems with every object changed. Only C4, Airlocks and Autolathe are confirmed to qdel properly after this fix. Also fixes objects not qdel()ing properly when destroyed with a C4.
=> Added qdel(wires) to a bunch of objects Destroy proc.

code/modules/admin/verbs/debug.dm
both proc call verbs will now alert admins when used in addition to being logged
fixes #13707
=> admin messages for proc calls

code/__HELPERS/icon_smoothing.dm
This version skips touching the overlays list in the cases where it's not needed to update the corners.
=> Improved smooth_icon() speed on certain cases

code/game/objects/structures/grille.dm, code/game/objects/structures/window.dm, code/game/turfs/simulated.dm, code/game/turfs/simulated/floor.dm
Pipes and cables will now be protected from explosions until they are exposed. Being exposed means the turf they are on is not intact and there isn't a reinforced window or grille in the same turf.
Edit: If the affected turf is in devastating range protections won't work.
Fixes https://github.com/tgstation/-tg-station/issues/3513
Fixes https://github.com/tgstation/-tg-station/issues/14126
:cl:
tweak: Pipes and cables under walls, intact floors, grilles and reinforced windows will now be shielded from explosions.
/:cl:
=> Floor level objects will now be protected from explosions until they are exposed.

code/game/machinery/doors/airlock.dm
Fixes https://github.com/tgstation/-tg-station/issues/4304 - Airlock lights (access denied, opening, closing, bolts) turning on when airlock is unpowered.
Did not change bolt operation during no power mode because that's more of a feature request than a bug. Gameplay trumps realism for this, in my opinion. That change can be made after the freeze if people feel it's necessary.
=> Fixed airlock lights turning on when airlock is unpowered.

code/modules/mob/living/silicon/robot/emote.dm
Closes https://github.com/tgstation/-tg-station/issues/14938
:cl:
rscadd: Added a no power warning cyborg verb to Robot Commands.
/:cl:
=> Added a "no power" warning emote to cyborgs.

tools/mapmerge/Run Map Merge.bat, tools/mapmerge/map_helpers.py, tools/mapmerge/mapmerger.py
Fixes https://github.com/tgstation/-tg-station/issues/15715
Changed it so when the merger is ran in 'tgm' mode (default), the merged map will be written in tgm directly and with a custom map format (see https://gist.github.com/anonymous/3a3607baa60184ffd710). This new format avoids conflicts as much as possible.
What a map file will look like after being processed in 'tgm' mode:
"aYY" = (
/obj/machinery/atmospherics/pipe/simple/supply/hidden{
____dir = 4
____},
/turf/simulated/floor/carpet,
/area/library)
(127,1,1) = {"
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
aaa
...
aaa
"}
=> Map merger patch

code/__HELPERS/icon_smoothing.dm, code/game/turfs/simulated/walls_misc.dm
Fixed a runtime that breaks icon smoothing when atoms are spawned adjacent to map border.
Fixed a runtime when a diagonal wall is adjacent to a map border.
Added the ability for atoms to icon smooth with map border void.
=> Runtime fix, map border smoothing

code/modules/events/vent_clog.dm
An addition following the merging of https://github.com/tgstation/-tg-station/pull/15810
Cockroaches are ejected from scrubbers due to the back pressure. It turns out those pipes were home to resilient space cockroaches!
:cl:
rscadd: Scrubber clog event now ejects cockroaches.
/:cl:
Note: problem of sprites persists.
edit: New sprites were made.
=> Scrubber clog event now has a chance to spawn cockroaches.

code/modules/clothing/shoes/bananashoes.dm, code/modules/hydroponics/grown/banana.dm
- Fixed synthetic banana peels slipping for too long and not deleting themselves on slip
- Banana shoes can now take any item that has bananium in it, instead of just refined sheets
- Banana shoes have NOSLIP when turned on
:cl:
bugfix: Fixed the mk-honk prototype shoes.
/:cl:
=> Fixed and buffed the banana shoes

code/datums/ai_laws.dm, code/game/objects/items/weapons/AI_modules.dm, code/game/objects/structures/ai_core.dm
Fixes https://github.com/tgstation/tgstation/issues/10263
AI core laws datum is now initialized at ``New()`` according to server configuration and all law programming is preserved when the AI is made.
=> Changed AI core programming so it functions like the AI Upload.

code/modules/clothing/spacesuits/hardsuit.dm
Due to popular demand.
:cl:
rscdel: Engineering, CE and Atmos hardsuits no longer have in-built jetpacks.
/:cl:
=> Station hardsuits no longer have in-built jetpacks

code/__HELPERS/game.dm, code/_globalvars/lists/flavor_misc.dm, code/game/gamemodes/wizard/spellbook.dm, code/modules/spells/spell_types/spacetime_distortion.dm, tgstation.dme
This spell will distort spacetime around the wizard to make movement within it difficult, every step taking you into a different tile than the one you were expecting.
Using placeholder sprites, which don't look too bad but I'd rather something more appropriate if someone is willing to sprite.
:cl:
rscadd: New wizard spell: Spacetime Distortion.
/:cl:
Merge token: https://github.com/tgstation/tgstation/pull/18254
=> Wizard Spell: Spacetime Distortion

tools/mapmerge/map_helpers.py, tools/mapmerge/mapmerger.py
It was recycling keys that were still in use, when the model list wasn't ordered (likely happening because of git reverts). Solution: Sort it before doing anything.
Also added a method to print errors, added a preemptive check for key length difference, made it so the map is still converted to TGM when a key length difference is detected.
Fixes https://github.com/tgstation/tgstation/issues/17349
Fixes https://github.com/tgstation/tgstation/issues/19089
Merge this before any z2 edits as z2 merging is broken with the current version of the merging script.
=> Patched a mapmerger bug where it would incorrectly recycle keys.

code/modules/mob/living/carbon/human/species.dm
Fixes #19259 
Fixes #17746
:cl:
fix: Attacks will no longer miss missing limbs
/:cl:
=> fixes attacks missing due to dismemberment

tools/mapmerge/map_helpers.py
If you don't run (currently) 3.5 the script exits.
=> Added a Python version check to map_helpers.py.

tools/mapmerge/map_helpers.py, tools/mapmerge/mapmerger.py
Python version error message does not appear if you don't have pathlib, which you might not have if you're using 2.7.
Changed it to load map_helpers.py first so this works as intended.
=> [mapmerger] load python version test before everything else

code/game/objects/items/weapons/storage/fancy.dm, code/game/objects/items/weapons/storage/storage.dm
- Fixed candle boxes disappearing when trying to open them
- Changed ``storage_contents_dump_act()`` to use ``handle_item_insertion()`` instead of ``remove_from_storage()``
- When dumping from one storage to another or out on the floor, fancy storages will now update icon properly
:cl:
tweak: Opening and closing of donut boxes, etc. is now done with clicking the object with itself.
/:cl:
=> Fixed candle box icon bug and more

code/datums/martial.dm, code/game/objects/items/weapons/melee/misc.dm, code/game/objects/items/weapons/stunbaton.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/uplink/uplink_item.dm
fixes an abusive exploit and makes 2 combos easier to use, increases cqc harm damage, adds martial art block_chance var which is only activated if you have your throw_mode on for active defense.
baton blocks stun the person attempting the attack too, you can now block batons and then throw or chokehold.
:cl: Basilman
add: CQC users can now block attacks by having their throw mode on.
tweak: The CQC kick and Disorient-disarm combos are now much easier to use, CQC harm intent attacks are stronger aswell.
fix: Fixed being able to CQC restrain someone, let him go, then 10 minutes later disarm someone else to instantly chokehold them.
tweak: CQC costs more TC (13)
/:cl:
makes tc cost for CQC 13 with all the buffs.
=> CQC tweaks, improvements and fixes [and adds and utilizes martial art blocks)

code/game/gamemodes/changeling/traitor_chan.dm
After many horrific low pop rounds absolutely dominated by 2-3 changelings I've listened to the feedback of sybil and given traitor a minimum population limit of 25. This is roughly the same pop requirement for cult and I feel is a fair number of players to combat the changeling menace. I'll edit the requirement if people think it's too high.
Also, this is the first pr I've made so shit might be broke. point out any mistakes please.
:cl: Durkel
tweak: Recent enemy reports indicate that changelings have grown bored with attacking near desolate stations and have shifted focus to more fertile hunting grounds.
/:cl:
=> Gives traitorchan a minimum pop limit

tools/mapmerge/map_helpers.py
This was supposed to be part of the last patch but wasn't. 
Dictionary trimming is removing unused tiles from a map's dictionary to keep the bloat down.
Dictionary trimming will now trigger on maps with at least half of their tiles unused or at least 300 tiles unused. If this happens your map diffs will be huge, so don't panic. If this causes map conflicts to occur you can use the map conflict fixer to help solve that.
Edit, if a trimming is triggered a date stamp will be added as a commentary header to the file, like the TGM header. It looks like this:
``//Model dictionary trimmed on: 25-01-2017 22:49 (UTC)``
=> Map merger patch - dictionary trimming

tools/mapmerge/map_helpers.py
Added real support for map comments, the parser function will now skip over line comments. 
Everything after ``//`` is a line comment, unless these characters are inside quotes just to be safe. I don't know if byond is sensitive to quotes in this case, but I did it anyway.
A line comment ends after a line break.
This is a patch because merging a map with a trimming commentary results in a bad model being added.
=> Map merger patch - comments!

tools/mapmerge/map_helpers.py
Dictionary trimming only triggers at 1600 unused map models now.
=> [map merge] Reduce frequency of map trimming.

tools/mapmerge/map_helpers.py
So DM can sometimes write maps with duplicate models for no good reason and it was breaking the script. There is already one of these try catch in there but another one is necessary.
=> [map merger] Added try catch block to handle duplicate keys.

interface/interface.dm
This PR fixes the wiki button, which previously did nothing when pressed.
I also fixed a typo.
:cl: NewSta
fix: Fixes the wiki button
spellcheck: Fixes a typo in the wiki button description
/:cl:
=> Fixes the wiki button

code/game/objects/items/plushes.dm, code/modules/antagonists/cult/runes.dm
you can't use 9 nar-sie plushies to invoke a rune, nar-sie plushies are only counted once
:cl: Astral
add: blood cultists can now use a nar nar plushie as an extra invoker for runes!
/:cl:
=> A Nar-Sie Plushie can be used an an extra invoker now!

code/modules/power/turbine.dm
Fixes #35899
:cl: Astral
fix: Constructed turbines will now properly connect to the powernet
/:cl:
ok so i was browsing engineering autism and I saw this easy to fix issue mentioned.
=> Constructed turbines now properly connect_to_network()

code/game/objects/items/implants/implant_stealth.dm
changed the time to turn invisible from 0.5 seconds to 2 seconds
:cl: basilman
balance: changed the time for agent box to turn invisible from half a second to 2 seconds
/:cl:
[why]: # cuz it's too short and the few seconds at the beginning where it's highly visible are what matters
=> nerfs agent box a smidgen

code/modules/power/cell.dm, code/modules/power/powernet.dm
zippity zappity get off my praperty
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)
:cl: Kierany9
tweak: Electric shocks are no longer capped at a measly 90(+-5) damage, with a proper engine setup and hotwiring, electric shocks can now do up to 195(+-5). However, for the most part, shocks do less damage than before at charges under 2 MW.
/:cl:
[why]: # (Please add a short description [two lines down] of why …
=> Modifies the electrocution damage cap and scaling

code/datums/traits/negative.dm, code/modules/clothing/glasses/_glasses.dm
when i added the check cyberboss asked for, it'd do this weird thing where it splits the icon of the blindfold between your eyes and hands, but the true item would be in your hands
also fixed the blindfold changing color more than once (my bad)
:cl: Basilman
fix: fixed blindness identification blindfold changing color more than once
fix: fixed blindfold item being split in your inventory
/:cl:
=> fixes 2 minor blindness quirk bugs (thank u cyberboss)

code/modules/mob/living/bloodcrawl.dm
:cl: karma
fix: being able to pick up blood crawl items if they are dropped and being unable to drop them for the rest of the round is now fixed
/:cl:
=> Fixes blood crawl hands

code/modules/client/verbs/ooc.dm
> 
> steamport Today at 1:50 AM
> Hey
> can someone PR a change to /tg/?
> /client/verb/colorooc()
>     set name = "Set Your OOC Color"
>     set category = "Preferences"
> 
>     if(!holder || check_rights_for(src, R_ADMIN))
>         if(!is_content_unlocked())
>             return
> 
>     var/new_ooccolor = input(src, "Please select your OOC color.", "OOC color", prefs.ooccolor) as color|null
>     if(new_ooccolor)
>         prefs.ooccolor = sanitize_ooccolor(new_ooccolor)
>         prefs.save_preferences()
>     SSblackbox.record_feedback("tally", "admin_verb", 1, "Set OOC Color") //If you are copy-pasting this, ensure the 2nd parameter is unique to the new proc!
> return
> change 
> if(!holder || check_rights_for(src, R_ADMIN))
>  to 
> if(!holder || !check_rights_for(src, R_ADMIN)) …
=> Fix colorooc checking for R_ADMIN and byond

code/game/gamemodes/hivemind/radar.dm
:cl: Kierany9
fix: The Psychic Link pinpointer now works. Oops!
/:cl:
Closes #42514
Status effect checks return `FALSE` and not `null` causing the radar proc to runtime on the `?.` check that was requested by maintainers.
Would probably be a good idea to change all of those returns to `null` in the future
it makes the the gamemode work
=> Assimilation radar bugfix

code/modules/mob/living/carbon/damage_procs.dm
While looking to change how gaining traumas worked to make an alternative PR to #42610 I noticed some dodgy looking math that upon closer inspection did not do what it said it did. For those unaware, the chance to get a trauma rolls whenever you take brain damage above a certain point, and the intended formula is in a comment here:
>//Base chance is the hit damage; for every point of damage past the threshold the chance is increased by 2%
What that line of code actually did was have a base chance of **double the hit damage**, and the chance is increased 1% of the base chance (or 2% of the hit damage) for every point of damage past the threshold.
This changes the code to do what the comment says, but with a 1% chance instead of a 2% chance because rolling every tick is horrible. Ideally …
=> Trauma gain formula fix/tweak

code/game/gamemodes/hivemind/hivemind.dm, code/game/machinery/cloning.dm, code/modules/antagonists/hivemind/hivemind.dm, code/modules/antagonists/hivemind/vessel.dm, code/modules/spells/spell_types/hivemind.dm
Partially fixes #42767
- Fixed a null list runtime causing the track bonus not to work.
- Fixed an erroneous use of locate in the track bonus procs.
- Fixed a runtime that occurred due to a lack of mind checks.
- Fixed a runtime with the One Mind's objective being a string and not an objective datum.
- Added a couple of sanity checks.
- Removed a redundant callback.
- Fixed several runtimes due to a proc setting the One Mind team to `true` when an actual team had already been assigned to it.
- Fixed the remove_hivemember proc to work with minds instead of mobs.
- Vessels lose their vessel status upon being cloned (As was originally intended with assimilation being tied to the body).
- Vessels stop being woke when de-assimilated.
- Fixed vessels that aren't already woke not becoming antags …
=> Assimilation runtime & bug fixes

code/game/gamemodes/hivemind/radar.dm, code/modules/antagonists/hivemind/hivemind.dm
fixes the broken radars (again). the duration of a status effect, unless set on creation, is world.time+duration  [(See here)](https://github.com/tgstation/tgstation/blob/9d28bd7244844dba26ca213aca64f1295fc2eeeb/code/datums/status_effects/status_effect.dm#L28) and not just duration, which was causing them to expire instantly.
flips a couple of backwards conditionals (set to zero if can't find anything instead of can find anything), flips the receivers of a couple of messages (tested ingame, it was backwards).
it makes the mode work better
:cl:Kierany9
fix: The hivemind radar works again.
/:cl:
=> galaxy brain hivemind bugfixes

code/datums/martial/cqc.dm
:cl: Basilman
spellcheck: corrected CQC help instructions
/:cl:
=> Corrects CQC help instructions

code/modules/antagonists/hivemind/hivemind.dm, code/modules/antagonists/hivemind/vessel.dm
Does what it says in the title.
fixes bugs and reduces roundend screen clutter
:cl: Kierany9
fix: Fixed Hivemind Hosts retaining powers on death and while dead
/:cl:
=> Fixes hivemind hosts retaining powers on death/while dead and no longer displays objective status for One Mind vessels

code/modules/surgery/organs/heart.dm
:cl:
fix: Fixed cursed hearts maintaining red filter even when removed
/:cl:
closes #42384
=> Fixes cursed hearts maintaining red filter even when removed

code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/mob_helpers.dm
closes #43213 
:cl: Basilman
fix: fixed runtime from selectin missing bodypart due to ran_zone
code: changed how ran_zone selects a zone from a switch to pickweight
/:cl:
=> Fixes runtime from attempting checking armor on missing bodypart, improves ran_zone selection mechanism

code/modules/spells/spell_types/hivemind.dm
Fixes this bogus somebody just dm'd me about
>hey so, just wondering if this is intended behavior or not after a hivemind round again
>basically at the moment
>hiveminds can just immediately succumb if another one is killing them and avoid being reclaimed
>since reclaim doesnt work on hivemind bodies
prevents bad powergame
:cl: Kierany9
fix: Added a 15 second grace period after death to prevent people from avoiding a hivemind host's Reclaim by succumbing.
/:cl:
=> Reclaim now works for 15 seconds after death

code/modules/spells/spell_types/hivemind.dm
fixes the bug described in the title
bugs
:cl: Kierany9
fix: Chaos Induction no longer uses up its charge if you don't input an objective
/:cl:
=> Chaos Induction no longer uses up its charge if you don't input an objective

code/modules/spells/spell_types/hivemind.dm
What the title says, when the One Mind awakens the team gets an objective to ensure the boss, but this was simply to establish their goals as a team antagonist and not to determine whether they get the epic green text or not. It now succeeds as long as the original host survives the round instead of always failing.
it makes the red thing green when the boss doesn't die
:cl:Kierany9
fix: The One Mind team will now greentext if their leader survives
/:cl:
=> Changes the for-flavour One Mind objective into a functional Protect objective

code/modules/antagonists/hivemind/hivemind.dm
Fixes this garbage
> i think i found a major bug
> i mean an oversight
> for hivemind
> when a hivemind host dies, he loses all his vessels
> im pretty sure thats intended and all
> but it happens even when a onemind host dies
> and now a onemind host is immune to shit, has hivemind chat, but has 0 vessels and only roundstart abilities + onemind communications
fixes an oversight
:cl:Kierany9
tweak: Killing the One Mind's host now destroys the One Mind
fix: Fixes bugs related to this oversight
/:cl:
=> Killing the One Mind's host destroys the One Mind

code/game/gamemodes/hivemind/radar.dm, code/modules/spells/spell_types/hivemind.dm
just fyi this is a very long pr description for a bunch of 1 line changes
One of the first big updates to Assimilation changed the way outing worked, from a direct message on who assimilated the dude to a pinpointer-esque radar that shows you where they were. This PR implements two changes to this mechanic.
This one is somewhat simple, there is no longer a screen-wide radius around the target where the radar no longer works, but as you no longer need to scan the edge of the radius to find out who it is, the radar updates once every four seconds instead of every two.
To make a very long story short, if there were multiple hosts controlling one vessel, the radar would perform a weighted pick based on two things: proximity and a threat multiplier. Proximity is self-explanatory, and the …
=> Modifies how the Assimilation pinpointer radars work

code/modules/spells/spell_types/hivemind.dm
Alt title: **Reduces levels of salt generated by Queen's third studio album**
Gives Medullary Failure a maximum range of 7 (previously infinite) and prevents it from being used alongside Mind Control.
the people have spoken: it's not fun.
will probably replace with actual fun when life stops happening
:cl: Kierany9
balance: Medullary Failure now has a maximum range
/:cl:
=> Medullary Failure now has a maximum range

code/modules/spells/spell_types/hivemind.dm
#43978 messed up some of the logic in Network Invasion, causing it to not work after standing still instead of the other way around. This fixes that.
Also puts Sensory Shock, added in #44436, properly in the Hivemind Abilities panel instead of the Spells panel which happened due to it no longer being a child of spell/targeted_hive.
makes the gamemode work
:cl:
fixed: Fixed Network Invasion not working.
/:cl:
=> Fixes a bug in Network Invasion

code/modules/lighting/lighting_source.dm
Fixes https://github.com/tgstation/tgstation/issues/71826
Probably fixes some other issue related to lighting but i didn't find any
Look, i know it's called STATIC lighting for a reason, and movement on it should be kept to a minimum, but this at least ensure that static lighting being carried around, if that happens for some reason, updates properly.
:cl:
fix: Static light sources update properly now when carried by a mob.
/:cl:
=> Static light sources will attempt to follow the top atom

code/game/objects/items/melee/baton.dm, code/modules/mob/living/carbon/human/human_defense.dm
Basically, calls force say on humans that get electrocuted.
This also applies to baton hits, although they use a probability check.
I just think force_say() is a funny and underutilized feature of tgui say.
:cl:
add: Being electrocuted will most of the time make you blurt out whatever you were typing. This includes batons. Be careful.
/:cl:
=> Electrocution will cause you to blurt out whatever you were typing

code/modules/mob/living/carbon/human/species_types/android.dm, code/modules/surgery/bodyparts/species_parts/android_parts.dm, tgstation.dme
fixes https://github.com/tgstation/tgstation/issues/72771
more consistent species changing behavior
admittedly this is a bitch of a patchwork fix and surgically implanted limbs should be flagged as such to prevent being boofed by species changes, but ah well this is good enough for now
:cl:
fix: Transforming into an android and then back into another species will no longer leave you with permanent robotic limbs
/:cl:
=> android bodyparts no longer immune to species change

code/datums/components/crafting/guncrafting.dm, code/game/machinery/deployable.dm, code/game/objects/items/food/frozen.dm, code/game/objects/items/kitchen.dm, code/game/objects/items/storage/fancy.dm, code/game/objects/items/weaponry.dm, code/game/objects/structures/displaycase.dm, code/game/objects/structures/dresser.dm, code/game/objects/structures/noticeboard.dm, code/game/objects/structures/spirit_board.dm, code/modules/art/paintings.dm, code/modules/clothing/shoes/sandals.dm, code/modules/food_and_drinks/machinery/smartfridge.dm, code/modules/hydroponics/fermenting_barrel.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/photography/photos/frame.dm, code/modules/reagents/reagent_containers/cups/_cup.dm
This whole PR started because I realized that baseball bats are not actually flammable which I found weird, then I looked at a whole bunch of other stuff that really should be flammable but also isn't.
Makes wooden objects behave slightly more consistently? Honestly, most of these seem like oversights to me.
:cl:
balance: The following structures are now flammable: Picture frame, fermenting barrel, drying rack, sandals, painting frames, paintings, spirit board, notice board, dresser, displaycase chassis, wooden barricade
balance: The following items are now flammable: Baseball bat, rolling pin, mortar, coffee condiments display, sandals, wooden hatchet, gohei, popsicle stick, rifle stock
/:cl:
=> Makes a whole bunch of wooden objects flammable

.github/CODEOWNERS, code/__DEFINES/atmospherics/atmos_core.dm, code/game/objects/items.dm
Simply put, unless overriden, items with the ON_FIRE flag will always be at least 150º C (491,15 kelvin).
I didn't want to pack this change with https://github.com/tgstation/tgstation/pull/74803 because I feel this might have some weird unintended consequences, maybe.
Emergent gameplay like lighting a cigarette with a burning piece of paper, I guess.
:cl:
add: Burning items are now actually considered to be at a minimum, 150 degrees celsius by the game.
/:cl:
=> Makes burning items actually hot

code/datums/components/thermite.dm, code/datums/elements/rust.dm, code/game/objects/items/cigs_lighters.dm, code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
Nothing too interesting to be quite honest, just cleans up the thermite component code a bit because it was a bit weird.
This probably fixes a few rare bugs where the thermite overlay disappears due to an update_icon call. Slightly neater code.
Also, adds an examine message to thermite walls because small QoL stuff is neat.
:cl:
qol: Thermited walls now get an examine message telling you they are, in fact, thermited.
/:cl:
=> Cleans up thermite component code

code/modules/library/book.dm, code/modules/paperwork/paper.dm
For some reason, unlike other paper items, you couldn't ignite books with a lighter or other hot item.
Now, you can!
(Also made it so the odd obscure mechanic of cutting pages out of books can be done by any sharp item, not just wirecutters or knives)
Consistency. 
~~Burning copies of WGW.~~
:cl:
add: Books can now be burned just like any other paper item.
add: You can cut pages out of books with any sharp item, not just knives or wirecutters.
/:cl:
=> Adds book burning

code/__DEFINES/acid.dm, code/controllers/subsystem/processing/fire_burning.dm, code/datums/components/acid.dm, code/datums/components/burning.dm, code/game/atom_defense.dm, code/game/atoms.dm, code/game/machinery/_machinery.dm, code/game/objects/effects/particles/smoke.dm, code/game/objects/items.dm, code/game/objects/obj_defense.dm, code/game/objects/objs.dm, code/game/objects/structures/bonfire.dm, code/game/turfs/turf.dm, code/modules/vehicles/_vehicle.dm
Generally cleans up code on both components.
Moves burn proc back to /obj level, I'm not sure why I moved it to /atom level, it was unnecessary.
Acid component generalized so it can be used on any atom that uses atom_integrity.
Fixes a bug where objects that stopped burning didn't update their burn overlay properly due to bad removal logic and leftover code.
Standardizes examine messages on burning items by just slapping an examine signal registration on the component.
Adds fire particles to items thanks to Lemon's PR: https://github.com/tgstation/tgstation/pull/74524
Particles look cool
Bugfixes are good
Code improvements are good
:cl:
add: Burning items now get (small) smoke particles. Sick.
fix: Burning objects now clear their burning overlay properly.
qol: Examining burning objects …
=> Burning and acid components fixes and improvements

code/datums/status_effects/debuffs/fire_stacks.dm, code/game/objects/effects/particle_holder.dm
Basically, due to carbons using KEEP_TOGETHER, particles were appearing on the context menu which is annoying. I have no idea why it behaves like this.
Buuut, giving particle holders the KEEP_APART flag does fix this.
closes https://github.com/tgstation/tgstation/issues/75641
Bugfix good
no
=> Stops particle holders from appearing on context menu

code/datums/quirks/negative_quirks.dm
The knock out message will no longer appear if the quirk holder is already unconscious
Less confusing combat messages!
:cl:
fix: Glass joes will no longer appear to get knocked out, while already knocked out.
/:cl:
=> Glass jaw quirk minor oversight fix

code/modules/mob/living/carbon/human/species.dm
Fixes https://github.com/tgstation/tgstation/issues/75838
It's funny but it's a bad evil bug
:cl:
fix: Exotic blood types no longer persist through species change if the new species does not have an exotic blood type
/:cl:
=> Fixes exotic blood types persisting through species change

code/__DEFINES/dcs/signals/signals_object.dm, code/_onclick/item_attack.dm, code/datums/components/cult_ritual_item.dm, code/datums/components/explodable.dm, code/datums/components/food/ice_cream_holder.dm, code/datums/components/squeak.dm, code/datums/elements/bed_tucking.dm, code/datums/elements/loomable.dm
For some reason this was missed when moving attack_obj() to /atom level.
It peeves me that this signal is misnamed
=> Renames COMSIG_ITEM_ATTACK_OBJ to COMSIG_ITEM_ATTACK_ATOM

code/game/objects/items/devices/scanners/health_analyzer.dm, code/modules/surgery/organs/internal/liver/_liver.dm, code/modules/surgery/organs/internal/liver/liver_skeleton.dm
TRAIT_LIVERLESS_METABOLISM should do what it implies, and make you always metabolize as if you were liverless.
This was a stupid mistake on my part because I wasn't aware TRAIT_STABLELIVER was a thing.
TRAIT_LIVERLESS_METABOLISM and TRAIT_STABLELIVER should not behave the exact same.
Not quite player facing.
=> [NO GBP] Fixes dumb usage of TRAIT_LIVERLESS_METABOLISM i caused

code/__DEFINES/traits.dm, code/_globalvars/lists/objects.dm, code/datums/memory/key_memories.dm, code/datums/mood_events/drink_events.dm, code/datums/quirks/negative_quirks.dm, code/game/objects/items/cigs_lighters.dm, code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm, code/modules/reagents/reagent_containers/cups/glassbottle.dm
So you're telling me we have a smoker quirk and we DON'T have an alcoholic quirk?
What a travesty! Time to fix that.
This quirk is essentially equivalent to smoker, but instead of a favorite brand you get a favorite *brandy* (as in, favorite type of booze).
More quirk variety with decent roleplay value.
What will we do with a drunken sailor?
:cl:
add: Added Alcoholic as a negative quirk.
/:cl:
=> Alcoholic quirk

code/datums/brain_damage/mild.dm, code/modules/client/client_colour.dm
What the title says. 
The brain trauma makes the whole screen monochrome until cured.
I feel like the current pool for mild brain traumas is quite lame, this helps spice it up a bit with something that is quite annoying and distracting but not game breaking (as mild brain traumas should generally be).
:cl:
add: Added colorblindness as a mild brain trauma.
/:cl:
=> Adds colorblindness as a mild brain trauma

code/datums/bodypart_overlays/simple_bodypart_overlay.dm, code/datums/components/creamed.dm
Fixes https://github.com/tgstation/tgstation/issues/76641
Caused by the bodypart overlay being deleted before it got properly removed on UnregisterFromParent()
One less hard delete and one less bug caused by said hard delete
:cl:
fix: Creampies will no longer irreparably stain your face
/:cl:
=> Fixes water-resistant creampies
